version: '3.8'

services:
  app:
    build: .
    container_name: go-js-watcher-app
    ports:
      - "8090:8090"
    working_dir: /app
    volumes:
      - watcher_data:/app/data
    env_file:
      - .env
    environment:
      ENVIRONMENT: docker
      APP_BASE_URL: "${APP_BASE_URL:-http://localhost:8090}"
      PORT: 8090
      HOST: 0.0.0.0
    restart: unless-stopped

volumes:
  watcher_data:
    driver: local
